### PR TITLE
fix index.html, add npm dependencies

### PR DESCRIPTION
**Pull request by Murmurianez**
fix index.html
add npm dependencies

### CODE REVIEW

**Comment by Murmurianez** [comment]
Second commit is my mistake. I can't remove that =(

**Comment by timaschew** [comment]
Thanks @Murmurianez 
Somehow I missed your PR, so sorry for the delay.

The second commit was added to the pull request, because you used the same branch (master).
If you make pull requests and continue work on the fork you should always split these parts into different branches.

It's easy to fix this by:
1. Close this PR
2. Create a branch from your commit ab85f16 and do a PR from it

**Comment by timaschew** [comment]
Closing this PR, it's fixed in the master now

**Comment by timaschew** [comment]
User: https://github.com/lostwun

**Comment by timaschew** [comment]
User: https://github.com/miguelcostero

**Comment by timaschew** [comment]
User: https://github.com/damienroche

**Comment by timaschew** [comment]
User: https://github.com/deadcoder0904

**Comment by timaschew** [comment]
User: https://github.com/Murmurianez

**Comment by timaschew** [comment]
User: https://github.com/sumyfly

**Comment by timaschew** [comment]
User: https://github.com/adiutama

**Pull request closed without merging**
